[package]
name = "godot_cinema_rs"
version = "0.1.0"
authors = ["mucks <mail@mucks.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.7"
opencv = "0.29"
rodio = "0.10"

[lib]
crate-type = ["cdylib"]
